Repository beclab/market, pull requests merged in 2024-08, with the labels that each got.

#28 refactor: first load speed optimization
  frontend/src/App.vue
  frontend/src/components/appcard/AppCard.vue
  frontend/src/pages/application/CategoryPage.vue
  frontend/src/pages/application/HomePage.vue
  frontend/src/stores/app.ts
Labels: refactor

#29 fix: check user resource details
  frontend/src/stores/user.ts
Labels: fix

#30 feat: set gzip off
  nginx.conf
Labels: feat
